version: 2

jobs:
  # Build Gaia from the SDK source code specified by tasks/build/Gaia/COMMIT.sh.
  buildGaia:
    docker:
      - image: circleci/golang

    steps:
      - checkout

      - restore_cache:
          key: v5-Gaia-{{ checksum "tasks/build/Gaia/COMMIT.sh" }}

      # If Gaia isn't in the cache then build it.
      - run: |
          if [ ! -d ~/target ]; then
            cd tasks/build/Gaia
            . COMMIT.sh
            TARGET=~/target ./build.sh
          fi

      - save_cache:
          key: v5-Gaia-{{ checksum "tasks/build/Gaia/COMMIT.sh" }}
          paths:
            - ~/target

      - persist_to_workspace:
          root: ~/target
          paths:
            - "*"

  test:
    docker:
      - image: circleci/node:9.4.0-browsers

    environment:
      - BINARY_PATH: "/home/circleci/project/builds/Gaia/linux_amd64/gaiacli"
      - NODE_BINARY_PATH: "/home/circleci/project/builds/Gaia/linux_amd64/gaiad"

    steps:
      - checkout

      - attach_workspace:
          at: builds/Gaia

      - run: tasks/changelog-changed-check.sh

      - restore_cache:
          keys:
            - v1-dependencies-root-{{ checksum "package.json" }}
            - v1-dependencies-root-

      - run: yarn install

      - save_cache:
          paths:
            - yarn.lock
            - node_modules
          key: v1-dependencies-root-{{ checksum "package.json" }}

      - run:
          name: Test
          command: yarn run test
          no_output_timeout: 120

      - run:
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
          when: on_success

      - store_artifacts:
          path: testArtifacts

  # Build a release and publish it to GitHub.
  release:
    docker:
      - image: circleci/node:9.11.1

    steps:
      - checkout
      - run: sudo tasks/build/installWine.sh
      - run: yarn install

      - attach_workspace:
          at: builds/Gaia

      - run: node tasks/release.js

workflows:
  version: 2

  gaia-test-and-release:
    jobs:
      - buildGaia

      - test:
          requires:
            - buildGaia

      - release:
          requires:
            - buildGaia
            - test
          filters:
            branches:
              only: /release/
