version: '3'
services:
  caddy:
    image: "abiosoft/caddy:latest"
    volumes:
      - ./.caddy:/root/.caddy  # to save certificates on disk
      - ./Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "8080:8080"
    restart: "always"
    networks:
        - frontend

  # stargate:
  #   image: "lunie/gaia-script:latest"
  #   volumes:
  #     - ./nodes/stargate.sh:/etc/script.sh
  #   ports:
  #     - "1317:1317"

  node:
    image: "lunie/gaia-script:latest"
    container_name: node
    volumes:
      - ./nodes/first.sh:/etc/script.sh
      - ./node:/mnt/node
    expose:
      - 9070
    ports:
      - "26657:26657"
      - "9070:9070"
    restart: "always"
    networks:
        - frontend

networks:
    frontend: