version: '3'
services:
  proxy:
    image: "justsml/ssl-proxy:latest"
    environment:
      - HTTPS_PORT=8080
      - UPSTREAM_TARGET=node:9070
      - CERT_AUTO=true
      - SERVER_NAME=_
    ports:
      - "8080:8080"
    networks:
        - frontend
    links:
    - 'node:node'

  # stargate:
  #   image: "lunie/gaia-script:latest"
  #   volumes:
  #     - ./nodes/stargate.sh:/etc/script.sh
  #   ports:
  #     - "1317:1317"

  node:
    image: "lunie/gaia-script:latest"
    volumes:
      - ./nodes/first.sh:/etc/script.sh
      - ./node:/mnt/node
    expose:
      - 9070
    ports:
      - "26657:26657"
      - "9070:9070"
    networks:
        - frontend

networks:
    frontend: