version: '3'
services:
  caddy:
    image: "abiosoft/caddy:latest"
    volumes:
      - ./.caddy:/root/.caddy  # to save certificates on disk
      - ./Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: "always"
    networks:
        - frontend

  # stargate:
  #   image: "lunie/gaia-script:latest"
  #   volumes:
  #     - ./nodes/stargate.sh:/etc/script.sh
  #   ports:
  #     - "1317:1317"

  node:
    image: "lunie/gaia-script:latest"
    container_name: node
    environment:
      - RICH_ADDRESS=cosmos1ek9cd8ewgxg9w5xllq9um0uf4aaxaruvcw4v9e
    volumes:
      - ./nodes/first.sh:/etc/script.sh
      - ./node:/mnt/node
    expose:
      - 9070
      - 26657
    ports:
      - "26657:26657"
      - "9070:9070"
    restart: "always"
    networks:
        - frontend

  # node2:
  #   image: "lunie/gaia-script:latest"
  #   container_name: node
  #   volumes:
  #     - ./nodes/other.sh:/etc/script.sh
  #     - ./node:/mnt/node
  #   expose:
  #     - 9070
  #     - 26657
  #   ports:
  #     - "26657:26657"
  #     - "9070:9070"
  #   restart: "always"
  #   networks:
  #       - frontend

networks:
    frontend: