version: '3'
services:
  node:
    image: "tendermint/gaia:v0.34.1"
    container_name: node
    volumes:
      - ./nodes:/etc/nodes
      - ./node:/mnt/node
    entrypoint:
      - sh
      - /etc/nodes/first.sh
    expose:
      - 9070
      - 26657
      - 26656
    ports:
      - "26657:26657"
      - "9070:9070"
    restart: "always"
    networks:
        - frontend

  faucet:
    image: "tendermint/gaia:v0.34.1"
    environment:
      # mnemonic: 
      - RICH_ADDRESS=cosmos1ek9cd8ewgxg9w5xllq9um0uf4aaxaruvcw4v9e
    volumes:
      - ./nodes:/etc/nodes
      - ./node:/mnt/node
    entrypoint:
      - sh
      - /etc/nodes/faucet.sh
    restart: "always"
    networks:
        - frontend

  node2:
    image: "tendermint/gaia:v0.34.1"
    container_name: node2
    volumes:
      - ./nodes:/etc/nodes
      - ./node:/mnt/node
    entrypoint:
      - sh
      - /etc/nodes/secondary.sh
    restart: "always"
    networks:
        - frontend

networks:
    frontend: